Default: &defaults
  database: reyuzenfold.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: reyuzenfold_test.sqlite3
  <<: *defaults

Staging:
  database: reyuzenfold_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: reyuzenfold_production.sqlite3
  poolsize: 100
  <<: *defaults
